# Generated by Django 3.1.7 on 2021-04-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210331_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descrip',
            field=models.CharField(default='def', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
