# Generated by Django 3.1.7 on 2021-04-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210401_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descrip',
            new_name='description',
        ),
    ]
