# Generated by Django 3.1.2 on 2021-04-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210403_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproduct',
            name='user',
        ),
    ]
