# Generated by Django 3.1.2 on 2021-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_newproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproduct',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
