# Generated by Django 3.1.7 on 2021-04-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_product_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProduct',
        ),
    ]
