# Generated by Django 3.1.2 on 2021-04-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210405_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
