# Generated by Django 3.1.2 on 2021-04-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_delete_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orderproducts', to='pages.OrderProduct'),
        ),
    ]
