# Generated by Django 3.1.2 on 2021-04-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210406_1100'),
        ('pages', '0015_auto_20210406_2057'),
    ]

    operations = [
    ]
