# Generated by Django 3.1.2 on 2021-04-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_merge_20210407_0820'),
        ('pages', '0017_merge_20210407_0926'),
    ]

    operations = [
    ]
